# Converted from Azure DevOps Pipeline: Dotnet Nuget - cache clear - BET-AZ-Devops-01-Pool1 (BET-TFS1)
# Original ID: 3518

name: Dotnet Nuget - cache clear - BET-AZ-Devops-01-Pool1 (BET-TFS1)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # TODO: Convert specific Azure DevOps tasks to GitHub Actions
    # Original pipeline had 0 phases
    
    - name: Converted Build Step
      run: |
        echo "This workflow was converted from Azure DevOps"
        echo "Please review and update the steps as needed"
        echo "Original pipeline: Dotnet Nuget - cache clear - BET-AZ-Devops-01-Pool1 (BET-TFS1)"
