# Converted from Azure DevOps Pipeline: Dotnet Nuget - cache clear - BET-AZDevOps-01-Pool4 (BET-BLD-WIN02)
# Original ID: 3520

name: Dotnet Nuget - cache clear - BET-AZDevOps-01-Pool4 (BET-BLD-WIN02)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # TODO: Convert specific Azure DevOps tasks to GitHub Actions
    # Original pipeline had 0 phases
    
    - name: Converted Build Step
      run: |
        echo "This workflow was converted from Azure DevOps"
        echo "Please review and update the steps as needed"
        echo "Original pipeline: Dotnet Nuget - cache clear - BET-AZDevOps-01-Pool4 (BET-BLD-WIN02)"
