name: Verify Migration

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'GitHub org/owner'
        required: true
      repo:
        description: 'Repository name'
        required: true
  push:
    paths:
      - 'migration_reports/**'
      - 'scripts/verify-migration.ps1'

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: azure/setup-powershell@v1

      - name: Run verification
        id: verify
        shell: pwsh
        run: |
          $org = '${{ github.event.inputs.org || github.repository_owner }}'
          $repoInput = '${{ github.event.inputs.repo }}'
          if (-not $repoInput) { $repoInput = (Split-Path $env:GITHUB_REPOSITORY -Leaf) }
          $args = @('-Org', $org, '-Repo', $repoInput, '-Json', '-SummaryFile', 'verification-summary.json', '-LoadDotEnv')
          $ps = Join-Path $PWD 'scripts/verify-migration.ps1'
          Write-Host "Running: $ps $($args -join ' ')"
          $output = & $ps @args
          $exitCode = $LASTEXITCODE
          $output | Out-File verify-output.txt
          echo "json_output<<EOF" >> $GITHUB_OUTPUT
          echo $output >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "exit_code=$exitCode" >> $GITHUB_OUTPUT
          if (Test-Path verification-summary.json) { echo "summary_file=true" >> $GITHUB_OUTPUT }
          exit 0  # never fail here; handle later

      - name: Upload summary artifact
        if: steps.verify.outputs.summary_file == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: verification-summary
          path: verification-summary.json

      - name: Set job conclusion
        id: conclude
        run: |
          $exitCode = '${{ steps.verify.outputs.exit_code }}'
          if ($exitCode -eq '0') { echo "result=success" >> $GITHUB_OUTPUT }
          elseif ($exitCode -eq '2') { echo "result=neutral" >> $GITHUB_OUTPUT }
          else { echo "result=failure" >> $GITHUB_OUTPUT }

      - name: Post PR comment (if PR)
        if: github.event.pull_request && always()
        uses: actions/github-script@v7
        with:
          script: |
            const exitCode = '${{ steps.verify.outputs.exit_code }}';
            const body = [
              `### Migration Verification`,
              `Exit Code: ${exitCode}`,
              `Repository: ${{ github.event.inputs.org || github.repository_owner }}/${{ github.event.inputs.repo || github.event.repository.name }}`,
              `Result JSON (truncated):`,
              '```json',
              ( `${{ steps.verify.outputs.json_output }}`.substring(0, 4000) ),
              '```'
            ].join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Fail job if verification failed
        if: steps.conclude.outputs.result == 'failure'
        run: exit 1
